"""Auto-migration on startup

Revision ID: c3215212a5de
Revises: 76f2ddbba7af
Create Date: 2025-06-21 17:32:58.553809

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c3215212a5de"
down_revision = "76f2ddbba7af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_prices", schema=None) as batch_op:
        batch_op.drop_index("ix_stock_prices_stock_id")
        batch_op.drop_index("ix_stock_prices_trade_date")
        batch_op.drop_constraint("stock_prices_stock_id_trade_date_key", type_="unique")
        batch_op.create_unique_constraint("uq_stock_date", ["stock_id", "trade_date"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_prices", schema=None) as batch_op:
        batch_op.drop_constraint("uq_stock_date", type_="unique")
        batch_op.create_unique_constraint(
            "stock_prices_stock_id_trade_date_key", ["stock_id", "trade_date"]
        )
        batch_op.create_index("ix_stock_prices_trade_date", ["trade_date"], unique=False)
        batch_op.create_index("ix_stock_prices_stock_id", ["stock_id"], unique=False)

    # ### end Alembic commands ###
