"""add refresh token fields

Revision ID: d789e234f5a6
Revises: c1234567890a
Create Date: 2025-06-20 21:05:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d789e234f5a6"
down_revision = "c1234567890a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("refresh_token", sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column("refresh_token_expires", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("refresh_token_expires")
        batch_op.drop_column("refresh_token")

    # ### end Alembic commands ###
